	SUBROUTINE ATTEN(ED0MINUS,SPEC5KD,ED5INC)
	INCLUDE 'CommonKd.f'
	DIMENSION ED0MINUS(61),SPEC5KD(61),ED5INC(61)
C	WRITE(*,1001) TOTALZ,CANOPYHT   !debug
C  Depths are passed in Common statements
	ZTOC=TOTALZ-CANOPYHT	
	DO 100 I=1,61
	ED5INC(I)=ED0MINUS(I)*EXP(-SPEC5KD(I)*ZTOC)
C      WRITE(*,1001)SPEC5KD(I),EDINC(I)
C 1001  FORMAT(8X,'In s/r ATTEN, TOTALZ, CANOPYHT= '2f12.4) !debug     
 100	CONTINUE        
 	RETURN
 	END		
